disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - todo
  - notification_center_detachment

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - CravingForSound/Resources/R.generated.swift
  - Common/Common/Resources/R.generated.swift

identifier_name:  
  excluded:
    - id
    - rx
    - it
    - p1
    - p2
    - up
    - tx
    - ty
    - to
    - it
    - x
    - y
    - tx
    - ty
    - at
    - bg

type_name:  
  excluded:
    - E
    - O
    - T

line_length: 130
function_body_length: 60

type_body_length:
  - 500 # warning
  - 700 # error

file_length:
  warning: 600
  error: 1000

superfluous_disable_command:
  severity: warning

cyclomatic_complexity:
  - 13 # warning
