//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift

/// This `R` struct is generated and contains references to static resources.
public struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  public static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  public struct string {
    /// This `R.string.common` struct is generated, and contains static references to 5 localization keys.
    public struct common {
      /// Value: Artist
      public static let artist = Rswift.StringResource(key: "artist", tableName: "Common", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Check your internet connection
      public static let checkConnection = Rswift.StringResource(key: "check.connection", tableName: "Common", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Search
      public static let search = Rswift.StringResource(key: "search", tableName: "Common", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Something goes wrong
      public static let somethingGoesWrong = Rswift.StringResource(key: "something.goes.wrong", tableName: "Common", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Stored albums
      public static let albumsStored = Rswift.StringResource(key: "albums.stored", tableName: "Common", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: Artist
      public static func artist(_: Void = ()) -> String {
        return NSLocalizedString("artist", tableName: "Common", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Check your internet connection
      public static func checkConnection(_: Void = ()) -> String {
        return NSLocalizedString("check.connection", tableName: "Common", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Search
      public static func search(_: Void = ()) -> String {
        return NSLocalizedString("search", tableName: "Common", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Something goes wrong
      public static func somethingGoesWrong(_: Void = ()) -> String {
        return NSLocalizedString("something.goes.wrong", tableName: "Common", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Stored albums
      public static func albumsStored(_: Void = ()) -> String {
        return NSLocalizedString("albums.stored", tableName: "Common", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

public struct _R {
  fileprivate init() {}
}
